apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
      - name: bankapp
        image: cary01/bankapp:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: bankapp-env
